apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: updater-example
  namespace: argocd
  annotations:
    "argocd-image-updater.argoproj.io/image-list": alias-updater=sqymg/argocd-updater-example
    "argocd-image-updater.argoproj.io/alias-updater.update-strategy": latest
spec:
  project: default
  source:
    repoURL: https://github.com/mariogarcia/argocd-updater-example.git
    targetRevision: HEAD
    path: mode-argocd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: updater-example
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m