apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: updater-example
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sqymg/argocd-updater-example:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: updater-example
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80